# name: CI/CD for Ticket Forecast Use Cases

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   workflow_dispatch:

# jobs:
#   run-forecast-pipelines:
#     runs-on: windows-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: 3.11

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run Use Case 1
#       run: python src/run_usecase1.py

#     - name: Run Use Case 2
#       run: python src/run_usecase2.py

#     - name: Archive Use Case 1 Outputs
#       uses: actions/upload-artifact@v4
#       with:
#         name: usecase1-outputs
#         path: outputs/usecase1/**

#     - name: Archive Use Case 2 Forecast Plots
#       uses: actions/upload-artifact@v4
#       with:
#         name: usecase2-forecast-plots
#         path: outputs/usecase2/**
name: Ticket Forecast CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: 🛎️ Checkout Repository
      uses: actions/checkout@v4

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 📦 Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: ⚙️ Run Use Case 1
      run: python src/run_usecase1.py

    - name: ⚙️ Run Use Case 2
      run: python src/run_usecase2.py

    - name: 🚀 Deploy to ~/ticket_deploy
      run: |
        echo "📁 Deploying to ~/ticket_deploy"
        DEPLOY_PATH=$HOME/ticket_deploy

        # Create base structure
        mkdir -p $DEPLOY_PATH/usecase1/models
        mkdir -p $DEPLOY_PATH/usecase2/models
        mkdir -p $DEPLOY_PATH/usecase1/outputs
        mkdir -p $DEPLOY_PATH/usecase2/outputs

        # Copy models
        cp models/usecase1_model.pkl $DEPLOY_PATH/usecase1/models/
        cp models/usecase2_model.pkl $DEPLOY_PATH/usecase2/models/

        # Get latest output timestamp folders
        UC1_OUTPUT=$(ls -td outputs/usecase1/*/ | head -n 1)
        UC2_OUTPUT=$(ls -td outputs/usecase2/*/ | head -n 1)

        # Copy outputs
        cp -r "$UC1_OUTPUT" $DEPLOY_PATH/usecase1/outputs/
        cp -r "$UC2_OUTPUT" $DEPLOY_PATH/usecase2/outputs/

        echo "✅ Deployment successful to $DEPLOY_PATH"
