name: CI/CD for Ticket Forecast Use Cases

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-forecast-pipelines:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Use Case 1
      run: python src/run_usecase1.py

    - name: Run Use Case 2
      run: python src/run_usecase2.py

    - name: Archive Use Case 1 Outputs
      uses: actions/upload-artifact@v4
      with:
        name: usecase1-outputs
        path: outputs/usecase1/**

    - name: Archive Use Case 2 Forecast Plots
      uses: actions/upload-artifact@v4
      with:
        name: usecase2-forecast-plots
        path: outputs/usecase2/**
